// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleX.Infrastructure.Data;

#nullable disable

namespace ScheduleX.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501133924_IdentityInit")]
    partial class IdentityInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicYearId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AcademicYearId");

                    b.ToTable("TblAcademicYear", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.BreakRule", b =>
                {
                    b.Property<int>("BreakRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BreakRuleId"));

                    b.Property<byte>("AfterLectureNo")
                        .HasColumnType("tinyint");

                    b.Property<int>("BreakDurationMin")
                        .HasColumnType("int");

                    b.Property<string>("BreakName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("BreakNo")
                        .HasColumnType("tinyint");

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BreakRuleId");

                    b.HasIndex("ConfigId", "AfterLectureNo")
                        .IsUnique();

                    b.HasIndex("ConfigId", "BreakNo")
                        .IsUnique();

                    b.ToTable("TblBreakRule", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxSem")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasFilter("[CourseCode] IS NOT NULL");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TblCourse", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentCode")
                        .IsUnique()
                        .HasFilter("[DepartmentCode] IS NOT NULL");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("TblDepartment", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentStrength")
                        .HasColumnType("int");

                    b.HasKey("DivisionId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("SemesterId", "DivisionName")
                        .IsUnique();

                    b.ToTable("TblDivision", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.DivisionRoomAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("DivisionId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.HasIndex("SemesterId");

                    b.ToTable("TblDivisionRoomAllocation", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.ExternalFacultyPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("TblExternalFacultyPermission", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FacultyCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<byte?>("MaxLecturesPerDay")
                        .HasColumnType("tinyint");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FacultyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyCode")
                        .IsUnique()
                        .HasFilter("[FacultyCode] IS NOT NULL");

                    b.ToTable("TblFaculty", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.FacultyAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("FacultyId");

                    b.ToTable("TblFacultyAvailability", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("RoomType")
                        .HasColumnType("tinyint");

                    b.HasKey("RoomId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoomName")
                        .IsUnique();

                    b.ToTable("TblRoom", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.ScheduleConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LectureDurationMin")
                        .HasColumnType("int");

                    b.Property<byte>("LecturesPerDay")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("WorkingDaysMask")
                        .HasColumnType("int");

                    b.HasKey("ConfigId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TblScheduleConfig", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("SemesterNo")
                        .HasColumnType("tinyint");

                    b.HasKey("SemesterId");

                    b.HasIndex("CourseId", "SemesterNo")
                        .IsUnique();

                    b.ToTable("TblSemester", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SemesterStudentStrength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("SemesterStudentStrengths");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsElective")
                        .HasColumnType("bit");

                    b.Property<int>("PracticalCredits")
                        .HasColumnType("int");

                    b.Property<byte>("SubjectCategory")
                        .HasColumnType("tinyint");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TheoryCredits")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SubjectCode")
                        .IsUnique()
                        .HasFilter("[SubjectCode] IS NOT NULL");

                    b.ToTable("TblSubject", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectFaculty", b =>
                {
                    b.Property<int>("SubjectFacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectFacultyId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectSemesterId")
                        .HasColumnType("int");

                    b.Property<byte>("TeachingType")
                        .HasColumnType("tinyint");

                    b.HasKey("SubjectFacultyId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectSemesterId", "DivisionId", "TeachingType")
                        .IsUnique();

                    b.ToTable("TblSubjectFaculty", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectLectureConfig", b =>
                {
                    b.Property<int>("SubjectLectureConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectLectureConfigId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte?>("PracticalBlockSize")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PracticalLecturesPerWeek")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectSemesterId")
                        .HasColumnType("int");

                    b.Property<byte>("TheoryLecturesPerWeek")
                        .HasColumnType("tinyint");

                    b.HasKey("SubjectLectureConfigId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectSemesterId")
                        .IsUnique();

                    b.ToTable("TblSubjectLectureConfig", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectRoomConfig", b =>
                {
                    b.Property<int>("SubjectRoomConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectRoomConfigId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte?>("PreferredRoomType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectSemesterId")
                        .HasColumnType("int");

                    b.HasKey("SubjectRoomConfigId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectSemesterId")
                        .IsUnique();

                    b.ToTable("TblSubjectRoomConfig", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectSemester", b =>
                {
                    b.Property<int>("SubjectSemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectSemesterId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("SubjectSemesterId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId", "SemesterId")
                        .IsUnique();

                    b.ToTable("TblSubjectSemester", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TTCoordinatorCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("TblTTCoordinatorCourse", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSlotId"));

                    b.Property<int?>("BreakRuleId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<byte>("SlotNo")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SlotType")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("TimeSlotId");

                    b.HasIndex("BreakRuleId");

                    b.HasIndex("ConfigId", "SlotNo")
                        .IsUnique();

                    b.ToTable("TblTimeSlot", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActiveVersion")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ParentBatchId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ParentBatchId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TblTimeTableBatch", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableBatchSemester", b =>
                {
                    b.Property<int>("BatchSemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchSemesterId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("BatchSemesterId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("BatchId", "SemesterId")
                        .IsUnique();

                    b.ToTable("TblTimeTableBatchSemester", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("BlockPart")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<byte>("EntryType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectSemesterId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.HasKey("EntryId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectSemesterId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("BatchId", "DivisionId", "DayOfWeek", "TimeSlotId")
                        .IsUnique();

                    b.HasIndex("BatchId", "RoomId", "DayOfWeek", "TimeSlotId")
                        .IsUnique()
                        .HasFilter("[RoomId] IS NOT NULL");

                    b.ToTable("TblTimeTableEntry", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte>("LayoutType")
                        .HasColumnType("tinyint");

                    b.Property<string>("TemplateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TemplateId");

                    b.HasIndex("TemplateName")
                        .IsUnique();

                    b.ToTable("TblTimeTableTemplate", (string)null);
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("TblUser", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.BreakRule", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.ScheduleConfig", "ScheduleConfig")
                        .WithMany("BreakRules")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleConfig");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Course", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Division", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.AcademicYear", "AcademicYear")
                        .WithMany("Divisions")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Semester", "Semester")
                        .WithMany("Divisions")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.DivisionRoomAllocation", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Division", "Division")
                        .WithMany("DivisionRoomAllocations")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Room", "Room")
                        .WithMany("DivisionRoomAllocations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Semester", "Semester")
                        .WithMany("DivisionRoomAllocations")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Room");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.ExternalFacultyPermission", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Faculty", "Faculty")
                        .WithMany("ExternalPermissions")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Faculty", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Department", "Department")
                        .WithMany("Faculties")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.FacultyAvailability", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Faculty", "Faculty")
                        .WithMany("FacultyAvailabilities")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Room", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.ScheduleConfig", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.AcademicYear", "AcademicYear")
                        .WithMany("ScheduleConfigs")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Course", "Course")
                        .WithMany("ScheduleConfigs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.Department", "Department")
                        .WithMany("ScheduleConfigs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Semester", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Course", "Course")
                        .WithMany("Semesters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SemesterStudentStrength", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Subject", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectFaculty", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.AcademicYear", "AcademicYear")
                        .WithMany("SubjectFaculties")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Division", "Division")
                        .WithMany("SubjectFaculties")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Faculty", "Faculty")
                        .WithMany("SubjectFaculties")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Subject", null)
                        .WithMany("SubjectFaculties")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.SubjectSemester", "SubjectSemester")
                        .WithMany("SubjectFaculties")
                        .HasForeignKey("SubjectSemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Division");

                    b.Navigation("Faculty");

                    b.Navigation("SubjectSemester");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectLectureConfig", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.AcademicYear", "AcademicYear")
                        .WithMany("SubjectLectureConfigs")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Subject", null)
                        .WithMany("SubjectLectureConfigs")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.SubjectSemester", "SubjectSemester")
                        .WithMany("LectureConfigs")
                        .HasForeignKey("SubjectSemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("SubjectSemester");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectRoomConfig", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.Subject", null)
                        .WithMany("SubjectRoomConfigs")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.SubjectSemester", "SubjectSemester")
                        .WithMany("RoomConfigs")
                        .HasForeignKey("SubjectSemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("SubjectSemester");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectSemester", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Semester", "Semester")
                        .WithMany("SubjectSemesters")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Subject", "Subject")
                        .WithMany("SubjectSemesters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TTCoordinatorCourse", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Course", "Course")
                        .WithMany("TTCoordinatorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.User", "User")
                        .WithMany("TTCoordinatorCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeSlot", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.BreakRule", "BreakRule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("BreakRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.ScheduleConfig", "ScheduleConfig")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BreakRule");

                    b.Navigation("ScheduleConfig");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableBatch", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.AcademicYear", "AcademicYear")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.ScheduleConfig", "ScheduleConfig")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Course", "Course")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.User", "CreatedByUser")
                        .WithMany("CreatedBatches")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Department", "Department")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.TimeTableBatch", "ParentBatch")
                        .WithMany()
                        .HasForeignKey("ParentBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.TimeTableTemplate", "TimeTableTemplate")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Course");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Department");

                    b.Navigation("ParentBatch");

                    b.Navigation("ScheduleConfig");

                    b.Navigation("TimeTableTemplate");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableBatchSemester", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.TimeTableBatch", "TimeTableBatch")
                        .WithMany("BatchSemesters")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Semester", "Semester")
                        .WithMany("BatchSemesters")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("TimeTableBatch");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableEntry", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.TimeTableBatch", "TimeTableBatch")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Division", "Division")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.Room", "Room")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.Semester", "Semester")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleX.Core.Entities.SubjectSemester", "SubjectSemester")
                        .WithMany()
                        .HasForeignKey("SubjectSemesterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleX.Core.Entities.TimeSlot", "TimeSlot")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Room");

                    b.Navigation("Semester");

                    b.Navigation("SubjectSemester");

                    b.Navigation("TimeSlot");

                    b.Navigation("TimeTableBatch");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.User", b =>
                {
                    b.HasOne("ScheduleX.Core.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.AcademicYear", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("ScheduleConfigs");

                    b.Navigation("SubjectFaculties");

                    b.Navigation("SubjectLectureConfigs");

                    b.Navigation("TimeTableBatches");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.BreakRule", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Course", b =>
                {
                    b.Navigation("ScheduleConfigs");

                    b.Navigation("Semesters");

                    b.Navigation("Subjects");

                    b.Navigation("TTCoordinatorCourses");

                    b.Navigation("TimeTableBatches");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Faculties");

                    b.Navigation("Rooms");

                    b.Navigation("ScheduleConfigs");

                    b.Navigation("TimeTableBatches");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Division", b =>
                {
                    b.Navigation("DivisionRoomAllocations");

                    b.Navigation("SubjectFaculties");

                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Faculty", b =>
                {
                    b.Navigation("ExternalPermissions");

                    b.Navigation("FacultyAvailabilities");

                    b.Navigation("SubjectFaculties");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Room", b =>
                {
                    b.Navigation("DivisionRoomAllocations");

                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.ScheduleConfig", b =>
                {
                    b.Navigation("BreakRules");

                    b.Navigation("TimeSlots");

                    b.Navigation("TimeTableBatches");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Semester", b =>
                {
                    b.Navigation("BatchSemesters");

                    b.Navigation("DivisionRoomAllocations");

                    b.Navigation("Divisions");

                    b.Navigation("SubjectSemesters");

                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.Subject", b =>
                {
                    b.Navigation("SubjectFaculties");

                    b.Navigation("SubjectLectureConfigs");

                    b.Navigation("SubjectRoomConfigs");

                    b.Navigation("SubjectSemesters");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.SubjectSemester", b =>
                {
                    b.Navigation("LectureConfigs");

                    b.Navigation("RoomConfigs");

                    b.Navigation("SubjectFaculties");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeSlot", b =>
                {
                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableBatch", b =>
                {
                    b.Navigation("BatchSemesters");

                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.TimeTableTemplate", b =>
                {
                    b.Navigation("TimeTableBatches");
                });

            modelBuilder.Entity("ScheduleX.Core.Entities.User", b =>
                {
                    b.Navigation("CreatedBatches");

                    b.Navigation("TTCoordinatorCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
